- name: install molly-guard and pgrep
  apt:
    pkg:
      - molly-guard
      - pgrep

- name: make sure sysadmin does not reboot machine with patroni running
  copy: src=40-ensure-patroni-stopped dest=/etc/molly-guard/run.d/
  
