---
# TODO: split this
# TODO: "config" tag doesn't make any sense or does it?

- import_tasks: systemd-backports.yml
  when: (ansible_distribution_release == "stretch")

- name: Install patroni package
  package:
    name: patroni
    state: present

- name: Install consul client package
  package:
    name: python3-consul
    state: present
  when: dcs == "consul"

- name: Install zookeeper client package
  package:
    name: python3-kazoo
    state: present
  when: dcs == "zookeeper"

- name: Install etcd client package
  package:
    name: python3-etcd
    state: present
  when: dcs == "etcd"

- name: Install vip-manager package
  package:
    name: vip-manager
    state: present
  when: vip is defined and vip != ""

- block:
  
  - set_fact:
      version_dash_cluster_name: "{{ postgresql_major_version }}-{{ postgresql_cluster_name }}"
  
  - set_fact:
      patroni_config_file: "/etc/patroni/{{ version_dash_cluster_name }}.yml"
      vip_config_file:     "/etc/patroni/{{ version_dash_cluster_name }}.vip"

  - include: create_patroni_config_file.yml

  - include: create_vip-manager_config.yml

  - name: make sure patroni is running
    systemd:
      name: patroni@{{ postgresql_major_version }}-{{ postgresql_cluster_name }}
      state: started
      enabled: yes
  
  - name: make sure vip-manager is running
    systemd:
      name: vip-manager@{{ postgresql_major_version }}-{{ postgresql_cluster_name }}
      state: started
      enabled: yes
    when: vip is defined and vip != ""

  # block tag:
  tags: config
