---

- name: Setup backports repository
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian stretch-backports main'
    filename: 'backports'
    update_cache: true
  when: (ansible_distribution_release == "stretch")

- name: Install systemd from backports
  apt:
    name: systemd
    default_release: stretch-backports
    state: latest
  notify: reload systemd
  when: (ansible_distribution_release == "stretch")
