---
- name: Setup facts
  hosts: all
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: tasks/set_dcs_ips.yml
      tags: always

- name: Setup DCS servers
  hosts: dcs_servers
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - include: tasks/{{ dcs }}.yml


- name: Setup Postgres Servers
  hosts: pgsql_servers
  handlers:
    - include: handlers.yml
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
      tags:
        - config

  tasks:
    - include: tasks/consul.yml
      when: dcs == "consul"
    - include: tasks/postgresql.yml
    - include: tasks/patroni.yml
