---

- name: Install etcd package
  package:
    name: etcd-server
    state: present
  when: ((ansible_distribution_release != "stretch") and (ansible_distribution_release != "xenial"))

- name: Install etcd package
  package:
    name: etcd
    state: present
  when: (ansible_distribution_release == "xenial")

- name: Setup snapshot repository
  apt_repository:
    repo: 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20161015T102332Z/ testing main'
    filename: 'snapshot'
    update_cache: true
  when: (ansible_distribution_release == "stretch")

- name: Install etcd package
  package:
    name: etcd=2.3.7+dfsg-5
    state: present
  when: (ansible_distribution_release == "stretch")

- name: Enable client listen interface
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_LISTEN_CLIENT_URLS=\"http://localhost:2379,http://{{ hostvars['master']['ansible_eth0']['ipv4']['address'] }}:2379\""
    regexp: ".*ETCD_LISTEN_CLIENT_URLS.*"
  tags:
    - config

- name: Advertise client interface
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_ADVERTISE_CLIENT_URLS=\"http://{{ hostvars['master']['ansible_eth0']['ipv4']['address'] }}:2379,http://{{ hostvars['master']['ansible_eth0']['ipv4']['address'] }}:4001\""
    regexp: ".*ETCD_ADVERTISE_CLIENT_URLS.*"
  tags:
    - config

- name: systemctl daemon-reload / start etcd
  systemd:
    daemon_reload: yes
    name: etcd
    state: restarted
    enabled: yes
