- name: Install etcd-client
  apt: pkg=etcd-client

- name: Configure etcdctl settings
  lineinfile:
    dest: "/root/.bashrc"
    line: 'export ETCDCTL_API=3; export ETCDCTL_CACERT=/etc/etcd/ca.cert.pem; export ETCDCTL_CERT=/etc/etcd/{{ ansible_hostname }}.cert.pem; export ETCDCTL_KEY=/etc/etcd/{{ ansible_hostname }}.key.pem; export ETCDCTL_ENDPOINTS="{{ protocol }}://{{ etcd_host_ip }}:2379,http://{{ etcd_host_ip }}:4001"'
    regexp: "^export ETCDCTL_API=3; ETCDCTL_CACERT.*"
  when: use_certificates is defined and use_certificates
