---

- import_tasks: systemd-backports.yml
  when: (ansible_distribution_release == "stretch")

- name: Install patroni package
  package:
    name: patroni
    state: present

- name: Install consul client package
  package:
    name: python3-consul
    state: present
  when: dcs == "consul"

- name: Install zookeeper client package
  package:
    name: python3-kazoo
    state: present
  when: dcs == "zookeeper"

- name: Install etcd client package
  package:
    name: python3-etcd
    state: present
  when: dcs == "etcd"

- name: Install vip-manager package
  package:
    name: vip-manager
    state: present
  when: vip is defined and vip != ""

- name: Deploy patroni DCS config
  template:
    src: templates/dcs.yml
    dest: /etc/patroni/dcs.yml
    mode: 0640
    owner: "postgres"
    group: "postgres"
  notify: restart patroni
  tags:
    - config

- name: Deploy patroni config templates
  template:
    src: templates/config.yml.in
    dest: /etc/patroni/config.yml.in
    mode: 0640
    owner: "postgres"
    group: "postgres"
  notify: restart patroni
  tags:
    - config

- name: Create patroni configuration
  command: pg_createconfig_patroni --force --hostip={{ ansible_default_ipv4.address }} {% if postgresql_port is defined %}--port={{ postgresql_port }}{% endif %} {% if vip is defined %}--vip={{ vip }}{% endif %} {{ postgresql_major_version }} {{ postgresql_cluster_name }}
  notify:
    - restart patroni
    - restart vip-manager
  tags:
    - config
