---

- import_tasks: systemd-backports.yml
  when: (ansible_distribution_release == "stretch")

- name: Install patroni package
  package:
    name: patroni
    state: present

- name: Install consul client package
  package:
    name: python3-consul
    state: present
  when: dcs == "consul"

- name: Install zookeeper client package
  package:
    name: python3-kazoo
    state: present
  when: dcs == "zookeeper"

- name: Install etcd client package
  package:
    name: python3-etcd
    state: present
  when: dcs == "etcd"

- name: Install vip-manager package
  package:
    name: vip-manager
    state: present
  when: vip is defined and vip != ""

- block:
  - name: Deploy patroni DCS config
    template:
      src: templates/dcs.yml
      dest: /etc/patroni/dcs.yml
      mode: 0640
      owner: "postgres"
      group: "postgres"
    notify: restart patroni
  
  - name: Deploy patroni config templates
    template:
      src: templates/config.yml.in
      dest: /etc/patroni/config.yml.in
      mode: 0640
      owner: "postgres"
      group: "postgres"
    notify: restart patroni
  
  - include: tasks/create_patroni_config_file.yml

- name: make sure patroni is running
  systemd:
    name: patroni@{{ postgresql_major_version }}-{{ postgresql_cluster_name }}
    state: started
    enabled: yes

- name: make sure vip-manager is running
  systemd:
    name: vip-manager@{{ postgresql_major_version }}-{{ postgresql_cluster_name }}
    state: started
    enabled: yes
  when: vip is defined and vip != ""

  # block tag:
  tags: config
