- set_fact:
    dcs_ips: "{{ dcs_ips | default([])+ [hostvars[item]['ansible_eth0']['ipv4']['address']] }}"
  with_items: "{{ groups['dcs_servers'] }}"
  when: dcs_server_ips is not defined

- set_fact:
    dcs_ips: "{{ dcs_server_ips }}"
  when: dcs_server_ips is defined


