---

- name: Install zookeeper package
  package:
    name: zookeeperd
    state: present

- name: Disable ipv6
  lineinfile:
    dest: "/etc/default/zookeeper"
    line: "JAVA_OPTS=\"-Djava.net.preferIPv4Stack=true\""
    regexp: ".*JAVA_OPTS.*"
  notify: restart zookeper
  tags:
    - config
