---

- name: Install postgresql-common
  package:
    name: postgresql-common
    state: present

- name: Disable auto creation of PostgreSQL clusters
  lineinfile:
    dest: "/etc/postgresql-common/createcluster.conf"
    line: "create_main_cluster = false" 
    regexp: ".*create_main_cluster.*"
  tags:
    - config

- name: Install PostgreSQL Server
  package:
    name:
      - "postgresql-{{ postgresql_major_version }}"
      - "postgresql-contrib-{{ postgresql_major_version }}"
      - "postgresql-client-{{ postgresql_major_version }}"
      - "postgresql"
    state: present

- name: Copy pgpass from template
  template:
    src: postgres_pgpass
    dest: /var/lib/postgresql/.pgpass
    mode: 0600
    owner: "postgres"
    group: "postgres"
