- name: Install etcd-client
  apt: pkg=etcd-client

- name: Check if /etc/bash_completion.d exists
  stat: path=/etc/bash_completion.d
  register: etc_bash_completion_d

- name: Add bash completions for etcd
  copy: src=bash_completion/etcdctl dest=/etc/bash_completion.d
  when: etc_bash_completion_d.stat.exists

- block:

  - name: Add etcdctl settings
    template:
      src: etcdctl_environment.j2
      dest: /root/.etcdctl_environment

  - name: Configure etcdctl settings
    lineinfile:
      dest: "/root/.bashrc"
      line: "source /root/.etcdctl_environment"
      regexp: "^source /root/.etcdctl_environment"

  when: use_certificates

