- block:
  - set_fact:
      etcd_proto: https
    when: use_certificates is defined and use_certificates

  - set_fact:
      etcd_proto: http
    when: use_certificates is not defined or not use_certificates

  - set_fact:
      etcd_host_ip: "{{ hostvars[ansible_hostname]['ansible_eth0']['ipv4']['address'] }}"

  - name: Set member name
    lineinfile:
      dest: "/etc/default/etcd"
      line: "ETCD_NAME=\"{{ ansible_hostname }}\""
      regexp: ".*ETCD_NAME.*"
    notify: restart etcd
  
  - name: Listen for other cluster peers
    lineinfile:
      dest: "/etc/default/etcd"
      line: "ETCD_LISTEN_PEER_URLS=\"{{ etcd_proto }}://{{ etcd_host_ip }}:2380\""
      regexp: ".*ETCD_LISTEN_PEER_URLS.*"
    notify: restart etcd
  
  - name: Setup advertised peer communication URL
    lineinfile:
      dest: "/etc/default/etcd"
      line: "ETCD_INITIAL_ADVERTISE_PEER_URLS=\"{{ etcd_proto }}://{{ etcd_host_ip }}:2380\""
      regexp: ".*ETCD_INITIAL_ADVERTISE_PEER_URLS.*"
    notify: restart etcd
  
  - name: Enable client listen interface
    lineinfile:
      dest: "/etc/default/etcd"
      line: "ETCD_LISTEN_CLIENT_URLS=\"{{ etcd_proto }}://localhost:2379,{{ etcd_proto }}://{{ etcd_host_ip }}:2379\""
      regexp: ".*ETCD_LISTEN_CLIENT_URLS.*"
    notify: restart etcd
  
  # ugly! Is there a better way?
  - name: Advertise client interface
    lineinfile:
      dest: "/etc/default/etcd"
      line: "ETCD_ADVERTISE_CLIENT_URLS=\"{% for ip in dcs_ips %}{{ etcd_proto }}://{{ ip }}:2379{% if not loop.last %},{% endif %}{% endfor %}\""
      regexp: ".*ETCD_ADVERTISE_CLIENT_URLS.*"
    notify: restart etcd
  
  # ugly! Is there a better way?
  - name: Setup URLs of initials members
    lineinfile:
      dest: "/etc/default/etcd"
      line: "ETCD_INITIAL_CLUSTER=\"{% for host in groups[dcs_servers_group] %}{{ host }}={{ etcd_proto }}://{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}:2380{% if not loop.last %},{% endif %}{% endfor %}\""
      regexp: ".*ETCD_INITIAL_CLUSTER.*"
    notify: restart etcd

  # block tag:
  tags:
    - config
