- block:
  - set_fact:
      etcd_proto: https
    when: use_certificates is defined and use_certificates

  - set_fact:
      etcd_proto: http
    when: use_certificates is not defined or not use_certificates

  - set_fact:
      etcd_host_ip: "{{ hostvars[ansible_hostname]['ansible_eth0']['ipv4']['address'] }}"

  - name: install /etc/default/etcd
    template:
      src: etcd.j2
      dest: /etc/default/etcd
    notify: restart etcd

  # block tag:
  tags:
    - config
