- block:
  - set_fact:
      etcd_proto: https
    when: use_certificates

  - set_fact:
      etcd_proto: http
    when: not use_certificates

  - set_fact:
      etcd_host_ip: "{{ hostvars[ansible_hostname].ansible_default_ipv4.address }}"

  - include_tasks: ../tasks/set_dcs_ips.yml

  - name: install /etc/default/etcd
    template:
      src: etcd.j2
      dest: /etc/default/etcd
    notify: restart etcd

  # block tag:
  tags:
    - config
