---
- block:
  - import_tasks: etcd_install_deb.yml
  - import_tasks: etcd_certificates.yml
    when: use_certificates
  - import_tasks: etcd_configure.yml
  - import_tasks: etcd_unmask_and_start.yml
  # this is not strictly required,
  # but convenient for debugging etc:
  - import_tasks: etcd_client.yml
  tags:
    - etcd
    - config
