---
- block:
  - include: etcd_install_deb.yml
  - include: etcd_configure.yml
  - include: etcd_certificates.yml
    when: use_certificates is defined and use_certificates
  - include: etcd_unmask_and_start.yml
  # this is not strictly required,
  # but convenient for debugging etc:
  - include: etcd_client.yml
  tags:
    - etcd
    - config
