- name: Allow client access from whole cluster to etcd
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
    proto: tcp
    to_port: "2379"
    comment: clients to etcd
  with_items: "{{ [ groups[dcs_servers_group], groups[pgsql_servers_group] ] | flatten }}"

- name: Allow peer access to etcd
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
    proto: tcp
    to_port: "2380"
    comment: peers to etcd
  with_items: "{{ groups[dcs_servers_group] }}"

